name: Train Model

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run training script
      run: |
        python train_model.py
        - name: Commit results
  run: |
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
    git add results/
    git commit -m "Add training results"
    git push
